// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PawPal.Api.Data;

#nullable disable

namespace PawPal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118165153_AddCalendarFeature")]
    partial class AddCalendarFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PawPal.Api.Models.Administrator", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.HasKey("IdKorisnik");

                    b.ToTable("Administratori");
                });

            modelBuilder.Entity("PawPal.Api.Models.Clanarina", b =>
                {
                    b.Property<int>("IdClanarina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClanarina"));

                    b.Property<DateTime>("DatumIstekaClanarina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumPocetkaClanarina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.Property<string>("StatusClanarina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VrstaClanarina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdClanarina");

                    b.HasIndex("IdKorisnik");

                    b.ToTable("Clanarine");
                });

            modelBuilder.Entity("PawPal.Api.Models.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdKorisnik"));

                    b.Property<string>("AuthProvider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmailKorisnik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LozinkaHashKorisnik")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfilnaKorisnik")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdKorisnik");

                    b.HasIndex("EmailKorisnik")
                        .IsUnique();

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("PawPal.Api.Models.Pas", b =>
                {
                    b.Property<int>("IdPas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPas"));

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.Property<string>("ImePas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Pasmina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Poslastice")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilnaPas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RazinaEnergije")
                        .HasColumnType("integer");

                    b.Property<string>("Socijalizacija")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Starost")
                        .HasColumnType("integer");

                    b.Property<string>("ZdravstveneNapomene")
                        .HasColumnType("text");

                    b.HasKey("IdPas");

                    b.HasIndex("IdKorisnik");

                    b.ToTable("Psi");
                });

            modelBuilder.Entity("PawPal.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdKorisnik");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("PawPal.Api.Models.Placanje", b =>
                {
                    b.Property<int>("IdPlacanje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlacanje"));

                    b.Property<DateTime>("DatumPlacanje")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdRezervacija")
                        .HasColumnType("integer");

                    b.Property<decimal>("IznosPlacanje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NacinPlacanje")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusPlacanje")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdPlacanje");

                    b.HasIndex("IdRezervacija");

                    b.ToTable("Placanja");
                });

            modelBuilder.Entity("PawPal.Api.Models.Poruka", b =>
                {
                    b.Property<int>("IdPoruka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPoruka"));

                    b.Property<DateTime>("DatumVrijemePoruka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotografijaPoruka")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.Property<int>("IdRezervacija")
                        .HasColumnType("integer");

                    b.Property<string>("TekstPoruka")
                        .HasColumnType("text");

                    b.HasKey("IdPoruka");

                    b.HasIndex("IdKorisnik");

                    b.HasIndex("IdRezervacija");

                    b.ToTable("Poruke");
                });

            modelBuilder.Entity("PawPal.Api.Models.PretplataVlasnikSetacNovosti", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.HasKey("IdKorisnik");

                    b.ToTable("Pretplate");
                });

            modelBuilder.Entity("PawPal.Api.Models.Recenzija", b =>
                {
                    b.Property<int>("IdRecenzija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecenzija"));

                    b.Property<DateTime>("DatumRecenzija")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotografijaRecenzija")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdRezervacija")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .HasColumnType("text");

                    b.Property<int>("Ocjena")
                        .HasColumnType("integer");

                    b.HasKey("IdRecenzija");

                    b.HasIndex("IdRezervacija");

                    b.HasIndex("Ocjena", "IdRezervacija");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("PawPal.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PawPal.Api.Models.Rezervacija", b =>
                {
                    b.Property<int>("IdRezervacija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRezervacija"));

                    b.Property<string>("AdresaPolaska")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DatumRezervacija")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumVrijemePolaska")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTermin")
                        .HasColumnType("integer");

                    b.Property<int>("IdVlasnik")
                        .HasColumnType("integer");

                    b.Property<string>("NapomenaRezervacija")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatusRezervacija")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VrstaSetnjaRezervacija")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdRezervacija");

                    b.HasIndex("IdTermin");

                    b.HasIndex("IdVlasnik");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("PawPal.Api.Models.RezervacijaPas", b =>
                {
                    b.Property<int>("IdRezervacija")
                        .HasColumnType("integer");

                    b.Property<int>("IdPas")
                        .HasColumnType("integer");

                    b.HasKey("IdRezervacija", "IdPas");

                    b.HasIndex("IdPas");

                    b.ToTable("RezervacijePsi");
                });

            modelBuilder.Entity("PawPal.Api.Models.Setac", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.Property<string>("ImeSetac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LokacijaSetac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrezimeSetac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfilnaSetac")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TelefonSetac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdKorisnik");

                    b.HasIndex("LokacijaSetac");

                    b.ToTable("Setaci");
                });

            modelBuilder.Entity("PawPal.Api.Models.Termin", b =>
                {
                    b.Property<int>("IdTermin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTermin"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("DatumVrijemePocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.Property<string>("LokacijaTermin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxDogs")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Trajanje")
                        .HasColumnType("interval");

                    b.Property<string>("VrstaSetnjaTermin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdTermin");

                    b.HasIndex("IdKorisnik");

                    b.HasIndex("Cijena", "IdKorisnik");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("PawPal.Api.Models.Vlasnik", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.HasKey("IdKorisnik");

                    b.ToTable("Vlasnici");
                });

            modelBuilder.Entity("PawPal.Api.Models.WalkerGoogleAuth", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .HasColumnType("integer");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdKorisnik");

                    b.ToTable("WalkerGoogleAuths");
                });

            modelBuilder.Entity("PawPal.Api.Models.Administrator", b =>
                {
                    b.HasOne("PawPal.Api.Models.Korisnik", "Korisnik")
                        .WithOne("Administrator")
                        .HasForeignKey("PawPal.Api.Models.Administrator", "IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.Clanarina", b =>
                {
                    b.HasOne("PawPal.Api.Models.Setac", "Setac")
                        .WithMany("Clanarine")
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setac");
                });

            modelBuilder.Entity("PawPal.Api.Models.Pas", b =>
                {
                    b.HasOne("PawPal.Api.Models.Vlasnik", "Vlasnik")
                        .WithMany("Psi")
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.PasswordResetToken", b =>
                {
                    b.HasOne("PawPal.Api.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.Placanje", b =>
                {
                    b.HasOne("PawPal.Api.Models.Rezervacija", "Rezervacija")
                        .WithMany("Placanja")
                        .HasForeignKey("IdRezervacija")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("PawPal.Api.Models.Poruka", b =>
                {
                    b.HasOne("PawPal.Api.Models.Korisnik", "Korisnik")
                        .WithMany("Poruke")
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawPal.Api.Models.Rezervacija", "Rezervacija")
                        .WithMany("Poruke")
                        .HasForeignKey("IdRezervacija")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("PawPal.Api.Models.PretplataVlasnikSetacNovosti", b =>
                {
                    b.HasOne("PawPal.Api.Models.Vlasnik", "Vlasnik")
                        .WithOne("Pretplata")
                        .HasForeignKey("PawPal.Api.Models.PretplataVlasnikSetacNovosti", "IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.Recenzija", b =>
                {
                    b.HasOne("PawPal.Api.Models.Rezervacija", "Rezervacija")
                        .WithMany("Recenzije")
                        .HasForeignKey("IdRezervacija")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("PawPal.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("PawPal.Api.Models.Korisnik", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PawPal.Api.Models.Rezervacija", b =>
                {
                    b.HasOne("PawPal.Api.Models.Termin", "Termin")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IdTermin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawPal.Api.Models.Vlasnik", "Vlasnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IdVlasnik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Termin");

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.RezervacijaPas", b =>
                {
                    b.HasOne("PawPal.Api.Models.Pas", "Pas")
                        .WithMany("RezervacijePsa")
                        .HasForeignKey("IdPas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawPal.Api.Models.Rezervacija", "Rezervacija")
                        .WithMany("PsiRezervacije")
                        .HasForeignKey("IdRezervacija")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pas");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("PawPal.Api.Models.Setac", b =>
                {
                    b.HasOne("PawPal.Api.Models.Korisnik", "Korisnik")
                        .WithOne("Setac")
                        .HasForeignKey("PawPal.Api.Models.Setac", "IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.Termin", b =>
                {
                    b.HasOne("PawPal.Api.Models.Setac", "Setac")
                        .WithMany("Termini")
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setac");
                });

            modelBuilder.Entity("PawPal.Api.Models.Vlasnik", b =>
                {
                    b.HasOne("PawPal.Api.Models.Korisnik", "Korisnik")
                        .WithOne("Vlasnik")
                        .HasForeignKey("PawPal.Api.Models.Vlasnik", "IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.WalkerGoogleAuth", b =>
                {
                    b.HasOne("PawPal.Api.Models.Setac", "Setac")
                        .WithOne("GoogleAuth")
                        .HasForeignKey("PawPal.Api.Models.WalkerGoogleAuth", "IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setac");
                });

            modelBuilder.Entity("PawPal.Api.Models.Korisnik", b =>
                {
                    b.Navigation("Administrator");

                    b.Navigation("Poruke");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Setac");

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("PawPal.Api.Models.Pas", b =>
                {
                    b.Navigation("RezervacijePsa");
                });

            modelBuilder.Entity("PawPal.Api.Models.Rezervacija", b =>
                {
                    b.Navigation("Placanja");

                    b.Navigation("Poruke");

                    b.Navigation("PsiRezervacije");

                    b.Navigation("Recenzije");
                });

            modelBuilder.Entity("PawPal.Api.Models.Setac", b =>
                {
                    b.Navigation("Clanarine");

                    b.Navigation("GoogleAuth");

                    b.Navigation("Termini");
                });

            modelBuilder.Entity("PawPal.Api.Models.Termin", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("PawPal.Api.Models.Vlasnik", b =>
                {
                    b.Navigation("Pretplata");

                    b.Navigation("Psi");

                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
